/**:
  ros__parameters:
    x0: -0.5
    y0: 0.7
    z0: 1.28
    obstacles/r: 0.038
    obstacles/x: [-0.5, 0.8, 0.4]
    obstacles/y: [-0.7, -0.8, 0.8]
    rate: 200
    arena_x_length: 4.0
    arena_y_length: 4.0
